"""initial schema

Revision ID: ad445ccc0480
Revises: 
Create Date: 2026-04-10 11:20:05.941610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad445ccc0480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_guid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('conversion_log',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_guid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fhir_count', sa.Integer(), nullable=True),
    sa.Column('openehr_count', sa.Integer(), nullable=True),
    sa.Column('omop_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('conversion_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_log_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('observation_cache',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_obs_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept_name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('source_obs_guid')
    )
    with op.batch_alter_table('observation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_cache_concept_guid'), ['concept_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_cache_org_guid'), ['org_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_cache_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('users',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_su', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fhir_representations',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('observation_cache_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_cache_guid'], ['observation_cache.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('fhir_representations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fhir_representations_observation_cache_guid'), ['observation_cache_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_representations_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('omop_measurements',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('observation_cache_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('measurement_concept_id', sa.String(length=128), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('measurement_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_as_number', sa.Float(), nullable=True),
    sa.Column('value_as_concept_id', sa.String(length=128), nullable=True),
    sa.Column('unit_concept_id', sa.String(length=128), nullable=True),
    sa.Column('unit_source_value', sa.String(length=64), nullable=True),
    sa.Column('measurement_source_value', sa.String(length=256), nullable=True),
    sa.Column('measurement_source_concept_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_cache_guid'], ['observation_cache.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('omop_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_omop_measurements_observation_cache_guid'), ['observation_cache_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_omop_measurements_person_id'), ['person_id'], unique=False)

    op.create_table('openehr_representations',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('observation_cache_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('archetype_id', sa.String(length=256), nullable=False),
    sa.Column('composition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_cache_guid'], ['observation_cache.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('openehr_representations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openehr_representations_observation_cache_guid'), ['observation_cache_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_openehr_representations_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('refresh_log',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_log')
    with op.batch_alter_table('openehr_representations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openehr_representations_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_openehr_representations_observation_cache_guid'))

    op.drop_table('openehr_representations')
    with op.batch_alter_table('omop_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_omop_measurements_person_id'))
        batch_op.drop_index(batch_op.f('ix_omop_measurements_observation_cache_guid'))

    op.drop_table('omop_measurements')
    with op.batch_alter_table('fhir_representations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_representations_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_fhir_representations_observation_cache_guid'))

    op.drop_table('fhir_representations')
    op.drop_table('users')
    with op.batch_alter_table('observation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_cache_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_cache_org_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_cache_concept_guid'))

    op.drop_table('observation_cache')
    with op.batch_alter_table('conversion_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_log_patient_guid'))

    op.drop_table('conversion_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
